### ISSUE TITLE
Variable scoping is a bit concerning

### ISSUE THREAD

**Issue by colemickens** [equinix/metal-cli#33]
The codebase surprises me in some ways. For example, I was trying to understand how userdata was handled in `packet device create`. I was surprised to find that things like `alwaysPXE` or `hardwareReservationID` are effectively globals in the entire code base. I guess it doesn't wind up being an issue if the code is ever only used in this CLI context where it's always just one off invocations, but it still seems like a bit of a code smell. Has this been an issue in practice? What happens when two commands share flag names?

An example, when you look at "create_volume" you have to just know that most of the variables that are populated from the CLI  are defined in ... `create_device.go`. It would almost make more sense if all command flags were declared in a single file; and it would likely make it stick out more as a weird pattern, at least it does to me.

**Comment by colemickens** [comment]
I'm more accustomed to seeing a struct paired with each command, and the command's args are parsed into that struct. That way the model and command are in the same source code file and easy to grok, and you don't have to worry about the fact that any code anywhere can touch "projectId" and affect any command that might be in flight. (For example, I've previously been able to create composite cobra commands that effectively invoke other commands internally in sequence or parallel -- that would be impossible to do with the current lack of isolation between commands/invocations).

**Comment by jasmingacic** [comment]
We can refactor it. What are you suggesting?

**Comment by rusenask** [comment]
It would be better to group command options into structs like and drop `init()` functions:

```golang
type createOptions struct {
	name          string
        // more fields..
}

// then don't use init() in the file, there's no point, you can get the flags
// in the function itself:
func newCreateCommand(cli *command.CLI) *cobra.Command {
	opt := createOptions{}

	cmd := &cobra.Command{
		Use:   "create [OPTIONS]",
		Short: "Create something",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCreate(cli, opt)
		},
	}

	flags := cmd.Flags()
	flags.StringVar(&opt.name, "name", "", "Runner name")
	
	return cmd
}

```

Then each command could have their own options and not reuse them in an unknown ways. Also, in the example above I also pass `command.CLI` struct that holds:

```golang
type CLI struct {
	client api.APIClient
	config *config.Config
}
```

so we could get rid of global API client for packet and config that can include things like formatting (would be nice to have an option to remove this table wrapper, set default project ID).

It would be easier to do this in steps, maybe just start moving command groups into their own directories so everything is not in one package?

**Comment by jasmingacic** [comment]
It would make sense I agree. It is going to take a little more time to do it, as it might break the CLI.

As for global project-id the problem is with commands like `device get`, `volume get` and similar which are expecting either `project-id` or `id` so in the case of a global variable you wouldn't be able to use them. 
API is structured like this:
`projects/{project_id}/devices` to get all devices
`/devices/{device_id}` to get a single device
The challenge would be how to differentiate what the user is trying to achieve - fetch all or a single resource. 

Do you have any ideas how to do it?

**Comment by rusenask** [comment]
Maybe if nothing is given, check for default project ID?

```golang
var retriveDeviceCmd = &cobra.Command{
	Use:   "get",
	Short: "Retrieves device list or device details",
	Long: `Example:
	
packet device get --id [device_UUID]

	`,
	Run: func(cmd *cobra.Command, args []string) {

		if projectID == "" && deviceID == "" && defaultProjectID != "" {
			projectID = defaultProjectID
		}

```

Then it would just always list if nothing is given. 

Now I also see why servers are called devices :)

**Comment by jasmingacic** [comment]
p.s. I added alias  for device -> server

**Comment by displague** [comment]
I have a branch <https://github.com/packethost/packet-cli/compare/master...displague:project-id-from-config?expand=1> where I started experimenting with pulling the variables from the command context rather than using global variables:

```
projectID, _ = cmd.Flags().GetString("project-id")
```

It's also possible to access the variables through viper, which can inject environment variables and config file values when the command line argument is not set.
```
RunE : ... viper.GetString("project-id")

func init() {
	subCmd.Flags().StringVarP(&projectID, "project-id", "p", "", "UUID of the project")
	viper.BindPFlag("project-id", subCmd.Flags().Lookup("project-id"))
}
```

I haven't had success fetching the variable from the command line falling back to viper (env,config), yet.  It's strange to me that viper doesn't ask for the command context, but cobra has already routed us to the correct command by the time this function would be called.

The following block is working in that branch. Viper is an easy way to reduce conditions and gain functionality.

```patch
diff --git a/cmd/root.go b/cmd/root.go
index 6cd28ee..8d582b6 100644
--- a/cmd/root.go
+++ b/cmd/root.go
@@ -91,11 +91,9 @@ func initConfig() {
 		panic(fmt.Errorf("Could not read config: %s", err))
 	}
 
-	if viper.GetString("token") != "" {
-		packetToken = viper.GetString("token")
-	} else {
-		packetToken = os.Getenv("PACKET_TOKEN")
-	}
+	viper.SetEnvPrefix("PACKET")
+	viper.AutomaticEnv()
+	packetToken = viper.GetString("token")
 }
 
 func userHomeDir() string {
```

**Comment by displague** [comment]
Variables are now scoped within a function within the sub-package of the command.
