### ISSUE TITLE
`packet operating-systems get` does not return a list in a sorted order

### ISSUE THREAD

**Issue by vielmetti** [equinix/metal-cli#78]
### What happened?

I'm trying to figure out exactly how to provision a particular operating
system, and to determine what my choices are.

`packet-cli operating-systems get` looks like it's the right command,
but the list is very long, and it's not sorted, and I know that only 
some combination of operating systems and versions are available for
some machines.

At minimum it seems like the list should be returned in a stable, alphabetically
sorted order.

### How can we reproduce it?

`packet-cli operating-systems get`

CLI version (`packet --version`): packet version 0.0.8

**Comment by vielmetti** [comment]
Looks like the sort should go here

https://github.com/packethost/packet-cli/blob/master/cmd/retrieve_operating_system.go#L42-L44

**Comment by displague** [comment]
I'm not convinced that any particular order (outside of whatever the API naturally reports) would be best here.

However, like #80, the output format makes this rougher to use with `packet os get  | sort -t\| -k4`.

It would be nice to offer a `--no-something` option that removes the table header and footer. 
If the footer were removed in all cases, we could use `--no-header`.
If the `+` characters in the tables header were `|` we could call the default output format `Markdown` (we might have to escape some characters).
And we could introduce a `CSV` https://github.com/packethost/packet-cli/issues/81 (or TSV) output that might the output easier to work with from shell scripts.

semi-related? I am worried that we don't offer the best output fields currently, and any user pinning scripts to our current output fields will be ensnared by changes.

**Comment by displague** [comment]
#155 was introduced some time ago offering `--sort-by` and `--sort-dir` universal arguments.

However, packngo does not pass ListOptions in the OS List function, which means that these CLI arguments will not be sent to the API.  This should be addressed in packngo and then revisited here.

Ultimately, even with support for server-side sorting enabled for `metal operating-system get`, we would not see an immediate benefit because the operating-system end-point does not offer any sortable fields.

```
curl -X GET -H "X-Auth-Token: $METAL_AUTH_TOKEN" -H Content-Type:\ application/json 'https://api.equinix.com/metal/v1/operating-systems?sort_by=slug&sort_direction=asc' | jq '.operating_systems[].slug'
```
(I also tried `name`.)

For Metal CLI to get indirect support for sorted OSes from the API, this feature would need to be requested of the API.

For direct support, #183 by @cprivite offers some default local sorting behavior.
